### ISSUE TITLE
Export Dialogue as Spreadsheet URI Error

### ISSUE THREAD

**Issue by shrippen** [YarnSpinnerTool/VSCodeExtension#52]
**What is the current behavior?**

I want to use the included function to export the dialogue as a spreadsheet but this throws the following error:

```
Error in the language server: Error: Internal Error - System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at YarnLanguageServer.YarnLanguageServer.ExtractVoiceoverSpreadsheet(Workspace workspace, ExecuteCommandParams`1 commandParams) in /home/runner/work/VSCodeExtension/VSCodeExtension/YarnSpinner/YarnSpinner.LanguageServer/src/Server/YarnLanguageServer.cs:line 631
   at YarnLanguageServer.YarnLanguageServer.<>c__DisplayClass2_0.<ConfigureOptions>b__14(ExecuteCommandParams`1 commandParams) in /home/runner/work/VSCodeExtension/VSCodeExtension/YarnSpinner/YarnSpinner.LanguageServer/src/Server/YarnLanguageServer.cs:line 139
   at OmniSharp.Extensions.LanguageServer.Protocol.HandlerAdapter`1.<>c__DisplayClass3_0`2.<Adapt>b__0(TParams a, TCapability _, CancellationToken _)
   at OmniSharp.Extensions.LanguageServer.Protocol.LanguageProtocolDelegatingHandlers.Request`4.MediatR.IRequestHandler<TParams,TResult>.Handle(TParams request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerServiceCollectionExtensions.RequestHandlerDecorator`2.Handle(T request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
```

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

This error appears in the simplest of projects. I tried it with this script
`title: start
---
Hello
===`

**What is the expected behavior?**

An export of the dialogue

**Please tell us about your environment:**

  - Arch Linux 
  - Visual Studio Code 1.88.1
  - Extension Version: 2.4.6

**Comment by jacknkandy** [comment]
I got this same error message, except for the Preview Dialogue command first time trying after a new install. I just uninstalled and reinstalled and I got it to work. 

OSX Sonama 14.2.1
Visual Studio: 1.93.1
Extension Version: 2.4.6
